services:
  - type: web
    name: chat-geolocalizado-api
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php bin/console cache:warmup --env=prod
    startCommand: php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: "0"
      - key: APP_SECRET
        generateValue: true
      - key: APP_API_KEY
        value: test-api-key
      - key: DATABASE_URL
        fromDatabase:
          name: psql-postgres
          property: connectionString

databases:
  - name: psql-postgres
    plan: free
