services:
  - type: web
    name: chat-geolocalizado-api
    runtime: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: "0"
      - key: APP_SECRET
        generateValue: true
      - key: APP_API_KEY
        value: test-api-key
      - key: TRUSTED_PROXIES
        value: 127.0.0.1,REMOTE_ADDR
      - key: DATABASE_URL
        fromDatabase:
          name: psql-postgres
          property: connectionString

databases:
  - name: psql-postgres
    plan: free
